### PR TITLE
Add support for py3.11. Remove py27, py35, py36, py37

### PR DESCRIPTION
**Pull request by elacuesta**

### CODE REVIEW

**Comment by Gallaecio** [comment]
I’m taking this over, I would like it merged before https://github.com/scrapinghub/python-scrapinghub/pull/173.

**Comment by Gallaecio** [comment]
I believe the remaining issue affecting Python 3.10+ is https://github.com/kevin1024/vcrpy/issues/719. It is not entirely clear to me what’s the right fix to continue supporting Python 3.9 and earlier.

I have tried running `pytest --update-cassettes` locally as `docs/quickstart.rst` suggests, but it hangs on the very first test. I assume I am missing something, but I don’t know what.

**Comment by Gallaecio** [comment]
I cannot reproduce the pypy3 msgpack issue locally with the very same version of pypy :confused:

**Comment by Gallaecio** [comment]
> I cannot reproduce the pypy3 msgpack issue locally with the very same version of pypy 😕

It seems it was a temporary CI issue, it got past that now.

**Review by Gallaecio — APPROVED** [review]

**Review by wRAR — APPROVED** [review]

**Comment by branchvincent** [comment]
+1, looks ready to merge?

**Pull request merged**
