### PR TITLE
Add truncate method to collections

### PR DESCRIPTION
**Pull request by victor-torres**
This makes possible to delete an entire Collection with a single API request, without having to iterate through records and therefore making multiple API requests.

### CODE REVIEW

**Comment by victor-torres** [comment]
@vshlapakov @raphapassini @ejulio 

Could you review this pull request, please?

**Comment by raphapassini** [comment]
The code looks nice, I think you need to document this as well :)

**Comment by victor-torres** [comment]
> The code looks nice, I think you need to document this as well :)

Thanks. I've just updated the source code improving documentation, @raphapassini.

**Comment by vshlapakov** [comment]
@ejulio Agree, but the warning is related with a whole bunch of operations and not directly related with the changes, let's do it separately.

**Pull request merged**
