### PR TITLE
Unpin pytest

### PR DESCRIPTION
**Pull request by manycoding**
Just a small update.

### CODE REVIEW

**Comment by manycoding** [comment]
Wow, I am not sure why it fails.

**Comment by vshlapakov** [comment]
I did some tests, it seems there're breaking changes b/w pytest 3.2.5, that we use now, and the recent one 4.3.3, tests start failing on 3.7.1, that's reproducible locally. I do want to upgrade all the test dependencies (incl vcrpy) and simplify the whole cassettes-based testing approach, that's something for the next version of the library.

**Comment by manycoding** [comment]
@vshlapakov I created #120 to track it and am closing this one.

**Comment by vshlapakov** [comment]
Sounds good, thanks.

**Pull request closed without merging**
