### PR TITLE
Avoid races for hubstorage frontier tests

### PR DESCRIPTION
**Pull request by vshlapakov**
Looks like there're races in sh.hubstorage.frontier tests, it's relatively easy to reproduce by rerunning the Travis job (I can't reproduce it locally)
https://travis-ci.org/scrapinghub/python-scrapinghub/jobs/172664296

After checking internals, my guess is that as `Batchuploader` works in a separate thread trying to upload next messages batch from queue, and `frontier.flush()` operation waits for the queue being empty (by doing `queue.join()`),  there's a probability that on context switch the queue is empty, but `Batchuploader` hasn't called callback [yet](https://github.com/scrapinghub/python-scrapinghub/blob/master/scrapinghub/hubstorage/batchuploader.py#L120), and the `frontier.newcounter` is not updated yet. In this case simple short delay should fix this, at least I wasn't able to reproduce the issue after the fix.

Could you please confirm/disapprove my finding please?

### CODE REVIEW

**Comment by chekunkov** [comment]
@vshlapakov If there's an expectation that after a flush() counter will have a correct new value - IMO it's a bug and should be resolved by moving 

```
for _ in range(qiter.count):
    q.task_done()
```

after callback invocation [here](https://github.com/scrapinghub/python-scrapinghub/blob/master/scrapinghub/hubstorage/batchuploader.py#L130-L136).

**Comment by vshlapakov** [comment]
@chekunkov I'm not quite sure that there's such expectation, the original [PR](https://github.com/scrapinghub/python-hubstorage/pull/12) doesn't contain anything related to it. But from my pov with your change the logic would be more consistent, let's improve it.
@dangra Any objections ?

**Comment by chekunkov** [comment]
callbacks are only used in frontier afaik, operation in callback should be quick (parse json, increment count) - I don't think there are any downsides

**Comment by dangra** [comment]
> callbacks are only used in frontier afaik, operation in callback should be quick (parse json, increment count) - I don't think there are any downsides

As long as callbacks doesn't try to inject more items in the queue it will work, otherwise it deadlocks.

**Comment by vshlapakov** [comment]
@chekunkov @dangra Any pushback against the changes? I think it makes sense to drop a comment to avoid adding new elements in the queue with callbacks and merge the PR.

**Comment by chekunkov** [comment]
+1 to drop the comment and merge. I can hardly imagine reasons to store more items in the queue after successful POST request - writers should not generate items.

**Pull request merged**
